[package]
name = "dprint-plugin-rustfmt"
version = "0.1.0"
authors = ["David Sherret <dsherret@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
dprint-core = "0.22.0"
rustfmt-nightly = "1.4.18"
serde = { version = "1.0.88", features = ["derive"] }
serde_json = "1.0"

[profile.release]
lto = true
