[package]
name = "dprint-plugin-rustfmt"
version = "0.3.0"
authors = ["David Sherret <dsherret@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["lib", "cdylib"]

[features]
wasm = ["serde_json", "dprint-core/wasm"]

[dependencies]
dprint-core = { version = "0.27.0", features = [] }
rustfmt-nightly = { version = "=1.4.18" }
serde = { version = "1.0.88", features = ["derive"] }
serde_json = { version = "1.0", optional = true }

[patch.crates-io]
rustc-ap-rustc_data_structures = { path = "rustc_data_structures" }
